POST http://localhost:3000/convsvc HTTP/1.1

content-type: application/json
{
    "word": ["F", "L", "A", "S", "K"],
    "conditions": [[0, 0, 0, 1, 2],
                   [0, 0, 1, 1, 1],
                   [0, 0, 1, 0, 1],
                   [2, 0, 1, 1, 1],
                   [2, 2, 1, 1, 1],
                   [2, 2, 2, 2, 2]]
}